language: node_js
node_js:
  - node

# skip tests
install: true

deploy:
  - provider: script
    script: >-
      bash deploy.sh $ACCOUNT_ID $ZONE_ID
      $STUDENT_ROUTE $STUDENT_CHANNELS_TO_WEBHOOK_KV_NAMESPACES $STUDENT_USERS_KV_NAMESPACES
      $MENTOR_ROUTE $MENTOR_CHANNELS_TO_WEBHOOK_KV_NAMESPACES $MENTOR_USERS_KV_NAMESPACES
      $CF_API_KEY $CF_EMAIL
    skip_cleanup: true
    on:
      branch: master

before_install:
    - "npm i @cloudflare/wrangler -g"