type = "webpack"
name = "WORKER_NAME"
account_id = "ACCOUNT_ID"
zone_id = "ZONE_ID"
workers_dev = false

[env.student]
route = "STUDENT_ROUTE"
kv-namespaces = [
    { binding = "CHANNELS_TO_WEBHOOK", id = "STUDENT_CHANNELS_TO_WEBHOOK_KV_NAMESPACES" },
    { binding = "USERS", id = "STUDENT_USERS_KV_NAMESPACES" }
]

[env.mentor]
route = "MENTOR_ROUTE"
kv-namespaces = [
    { binding = "CHANNELS_TO_WEBHOOK", id = "MENTOR_CHANNELS_TO_WEBHOOK_KV_NAMESPACES" },
    { binding = "USERS", id = "MENTOR_USERS_KV_NAMESPACES" }
]